### ISSUE TITLE
Service worker redirect incorrect.

### ISSUE THREAD

**Issue by friedger** [gdg-x/hoverboard#149] opened 2016-10-02 21:18 UTC
I see an issue with service work on firefox at e.g. at https://devfest.be and https://devfest.gdg.org.ua/

It says something like "A service worker has handed over a "redirect" response to a FetchEvent.respondWith() although the RedirectMode was not 'follow'. Any ideas what is wrong? I have updated to v1.0.3.

To reproduce open the site in Firefox, then press refresh (F5 only).

**Comment by friedger** [comment] 2016-10-02 21:46
Is this related to https://github.com/w3c/ServiceWorker/issues/737?

**Comment by ozasadnyy** [comment] 2016-10-03 08:31
We are going to investigate this issue. Thanks, @friedger !

**Comment by MrCsabaToth** [comment] 2016-10-03 18:35
How is your PWA hosted?

**Comment by friedger** [comment] 2016-10-03 18:42
On firebase

**Comment by MrCsabaToth** [comment] 2016-10-03 20:49
develop or master branch? (I'm not sure if it matters)

**Comment by friedger** [comment] 2016-10-03 21:20
It is develop. Or cheery picked from there.

Source at github.com/BruGTUG/DevFest2016

**Comment by ozasadnyy** [comment] 2016-10-11 21:32
@friedger Have you made any changes to the code? I don't understand why I see this page: 
![devfest belgium 2016 2016-10-12 00-30-17](https://cloud.githubusercontent.com/assets/2954281/19289401/4dab7268-9013-11e6-8d09-2d5aa95e849e.png)

Is it hosted on Firebase hosting?

**Comment by friedger** [comment] 2016-10-12 05:22
Yes, I made this change as a workaround as I think the app shell needs more
work.

It is on firebase: devfest-belgium.firebaseapp.com

I don't see the SyntaxError, confusing.




[image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2016-10-11 23:32 GMT+02:00 Oleh Zasadnyy <notifications@github.com>:

**Comment by ozasadnyy** [comment] 2016-10-12 08:11
I have got it after a refresh on Firefox (MacOS). DevFest Ukraine website works ok. 
I recommend you to use the original solution.
Btw, I can't reproduce original issue. Could you send me more details?

**Comment by friedger** [comment] 2016-10-14 09:25
I am seeing the origin issue also with the DevFest Ukrain website. (Firefox on Windows):

Fehler beim Laden von 'https://devfest.gdg.org.ua/'. Ein ServiceWorker hat eine "redirect"-Antwort (Response) an FetchEvent.respondWith() übergeben, obwohl der RedirectMode nicht 'follow' war.service-worker.js:234:6

**Comment by dbs** [comment] 2016-11-02 15:02
We've been suffering from this as well, and we're also hosted on Firebase. I just merged & deployed the latest master from hoverboard and the problem is still there; we're at https://devfest.gdgsudbury.ca - this is from the console on Firefox 49 on Linux:

    Failed to load ‘https://devfest.gdgsudbury.ca/’. A ServiceWorker passed a redirected Response to FetchEvent.respondWith() while RedirectMode is not ‘follow’.

But if you access the site via https://gdg-sudbury-devfest.firebaseapp.com/ then reloading appears to work just fine.

**Comment by MrCsabaToth** [comment] 2016-11-02 15:44
Maybe it's something about configuration. The site URL is in several places, like https://github.com/gdgfresno/valleydevfest/blob/develop/data/hoverboard.config.json#L76 https://github.com/gdg-x/hoverboard/blob/master/index.html#L16 etc.

**Comment by dbs** [comment] 2016-11-02 16:53
http://stackoverflow.com/questions/40274429/corrupted-content-error-on-firefox-with-polymer-firebase makes me wonder if it's a common issue with polymer-cli (which depends on polymer-build, which depends on sw-precache to generate service-worker.js) on Firebase.

**Comment by htchien** [comment] 2016-11-24 05:24
Hi,

We also have this issue with our DevFest Taipei website:

https://devfest-taipei-3cbee.firebaseapp.com/

On Firefox Developer Edition v52 it would show the "Corrupted content error" page; And on Chrome v54 sometimes the local cache will be refreshed properly, but most of time it would just load the local cache version and would not refresh the site....

Is there a way to turn the local cache off in the ServiceWorker.js? This is really bothering us...

**Comment by MrCsabaToth** [comment] 2016-11-24 08:21
I accidentally came across this at DevFest SF: `reg.update();`

https://developers.google.com/web/fundamentals/instant-and-offline/service-worker/lifecycle#manual_updates

This `update` call basically makes it work as it should by default IMHO. The old worker won't linger around (for no reason) that much. I haven't tried this in production yet, just poked around and confirmed in a dev environ.

**Comment by htchien** [comment] 2016-11-24 09:59
@MrCsabaToth I believe in Hoverboard the service worker is not on in dev environ. unless I mis-understanding the code?

**Comment by MrCsabaToth** [comment] 2016-11-24 19:42
@htchien In my experience older service worker can get stuck even while developing. It helps if you work in a private window to start from a clean state. Manual update seems to solve that problem, as I mentioned it should be default behavior IMHO.

**Comment by htchien** [comment] 2016-11-26 08:07
I decided to remove the Service Worker on our DevFest site because it bothers us that the site cannot be refreshed properly while service working is on. If service worker can be fixed in the future then I will add it back.

**Comment by friedger** [comment] 2016-11-26 12:11
Fixing service-worker.js (install with fetch redirect: 'follow') manually seems to work.

**Comment by friedger** [comment] 2016-11-26 13:20
I have created an issue here: https://github.com/GoogleChrome/sw-precache/issues/220

**Closed** 2017-02-21 20:17 UTC
Labels: bug

**Comment by friedger** [comment] 2017-02-21 20:37
@ozasadnyy Thank you for the hard work and follow up!

**Comment by ozasadnyy** [comment] 2017-02-21 20:41
@friedger you are welcome :) Next time we should fixing such issues much faster!

**Comment by friedger** [comment] 2017-02-21 21:20
This one much dependent on Google's sw-precache

**Comment by hikeislife** [comment] 2020-08-05 05:33
you say this issue is fixed, but I am just now experiencing it, on both firefox and chrome (brave). the only diff is that firefox stays on oops page until I reload it, and chrome (brave) reloads itself split second later, but only after showing "the site can't be reached" - it's there long enough to read what it says before the reload occurs. the page is not hosted anywhere, I'm still in early stages of dev it's all happening on localhost

**Comment by abraham** [comment] 2020-09-02 02:40
@hikeislife This issue has been closed for a long time. Please open a new one and include as much details about what you are seeing as possible.
