### ISSUE TITLE
Cannot scroll speaker tiles

### ISSUE THREAD

**Issue by CaseyB** [gdg-x/hoverboard#326] opened 2017-09-28 15:36 UTC
we're using Hoverboard for our DevFest and the speaker tiles don't scroll on web or mobile. https://ohiodevfest.com I've tried in Chrome Version 61.0.3163.100 (Official Build) (64-bit) on Mac and my Pixel XL with Oreo.

**Comment by Splaktar** [comment] 2017-09-28 15:48
It's helpful to mention the exact version of Hoverboard that you are using. It looks like an older version around v1 from 2016?

Is the problem with scrolling vertically on a speaker page like https://ohiodevfest.com/speakers/14/?

**Comment by CaseyB** [comment] 2017-09-28 15:57
We're using v1.2.0 which looks like the latest release. You're correct we're having issues with the vertical scrolling on the page you linked to. Upon further investigation is appears to work in Safari but not in the versions of Chrome I mentioned.

**Comment by Splaktar** [comment] 2017-09-28 17:03
I saw that last year as well. It turned out to be due to some invisible element hovering over the component and stealing all mousescroll events.

I tried to reproduce it on https://hoverboard-master.firebaseapp.com/speakers/2/ but it seems to be working there.

**Comment by ozasadnyy** [comment] 2017-09-28 17:54
@CaseyB Are you talking about modals? If so it was fixed in https://github.com/gdg-x/hoverboard/commit/9b4271d37538e7c7abefe679b007d8b7c23df8e6
Please update to the latest commit in the master

**Comment by CaseyB** [comment] 2017-09-28 18:16
@ozasadnyy Yes, We will try this tonight! Thank you!

**Closed** 2017-12-27 15:55 UTC
